version: '3.8'

services:
  mariadb:
    image: ghcr.io/frickeldave/fd_mariadb:10.6.4-r1
    hostname: mariadb
    restart: "no"
    # volumes: # Tip: Disable for frequently recurring tests
    #   - mariadb-data:/home/appuser/data
    networks:
      kcnet:
        ipv4_address: 172.66.30.110
    healthcheck:
      test: "mysqladmin status -h 127.0.0.1 -u healthstatus -phealth2test -P 30110"
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      - MDB_ROOTPWD=root2test
      - MDB_PORT=30110
      - MDB_ADMINUSER=adminmdb
      - MDB_BACKUPUSER=backupmdb
      - MDB_ADMINPWD=admin2test
      - MDB_BACKUPPWD=backup2test
      - MDB_HEALTHUSER=healthstatus
      - MDB_HEALTHPWD=health2test
      - MDB_COLLATION=utf8_unicode_ci
      - MDB_CHARACTERSET=utf8
      - MDB_APPDB=keycloak
      - MDB_APPDB_USER=adminkeycloakdb
      - MDB_APPDB_PWD=adminkeycloakdb2test
  
  keycloak:
    image: ghcr.io/frickeldave/fd_keycloak:15.0.1
    entrypoint: /bin/sh -c 'echo "overridden entrypoint" > /tmp/test; tail -f /tmp/test;'
    hostname: keycloak
    restart: "no"
    # volumes: # Tip: Disable for frequently recurring tests
    #   - keycloak-data:/home/appuser/data
    networks:
      kcnet:
        ipv4_address: 172.66.30.120
    healthcheck:
      test: "curl --fail https://172.66.30.120:30120 --insecure || false"
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      - KC_AJPINTPORT=30124
      - KC_HTTPINTPORT=30121
      - KC_HTTPSINTPORT=30120
      - KC_MGNTHTTPINTPORT=30123
      - KC_MGNTHTTPSINTPORT=30122
      #- KC_MYSQLADMINUSER=adminmdb
      #- KC_MYSQLADMINPASSWORD=admin2test
      - KC_MYSQLHOST=172.66.30.110
      - KC_MYSQLPORT=30110
      - KC_MYSQLDB=keycloak
      - KC_MYSQLUSERNAME=adminkeycloakdb
      - KC_MYSQLPASSWORD=adminkeycloakdb2test
      - KC_MYSQLHEALTHUSER=healthstatus
      - KC_MYSQLHEALTHPWD=health2test
      - KC_BINDADDRESS=172.66.30.120
      #- KC_REMOVE_DB=true
      - KC_CERTPWD=cert2test
      - KC_ADMINUSER=kcadmin
      - KC_ADMINPWD=kcadmin2test
      - KC_CREATEINITREALM=true
      - KC_INITREALM=frickeldave
      - KC_INITUSERMAILDOMAIN=frickeldave.local
      - KC_INITUSERPASSWORD=init2test
      - CRT_VALIDITY=3650
      - CRT_C=DE
      - CRT_S=BAVARIAN
      - CRT_L=ISMANING
      - CRT_OU=FRICKELDAVE.LOCAL
      - CRT_CN=KEYCLOAK.FRICKELDAVE.LOCAL
networks:
  kcnet:
    ipam:
      driver: default
      config:
        - subnet: "172.66.30.0/24"
volumes:
  mariadb-data:
  keycloak-data: