USE mysql;
CREATE DATABASE IF NOT EXISTS #KC_MYSQLDB# CHARACTER SET=utf8 COLLATE=utf8_unicode_ci;
CREATE USER IF NOT EXISTS '#KC_MYSQLUSERNAME#'@'%' IDENTIFIED BY '#KC_MYSQLPASSWORD#';
GRANT ALL PRIVILEGES ON #KC_MYSQLDB#.* TO '#KC_MYSQLUSERNAME#'@'%';
FLUSH PRIVILEGES;